language: node_js
node_js:
  - "7"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - grunt build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "backbone-flickr.com"
  acl: public_read
  skip_cleanup: true
  local_dir: dist
branches:
  only:
    - master
