language: node_js
node_js:
  - "7"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
deploy:
  - provider: script
    script:
      - sudo apt-get update && sudo apt-get install -y python-dev
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - sudo python get-pip.py
      - sudo pip install --ignore-installed awscli
      - grunt build
      - aws s3 sync ./dist/ s3://backbone-flickr.com/ --acl public-read
    on:
      branch: master
