language: node_js
node_js:
  - "7"
addons:
  apt:
    packages:
      - python-dev
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install awscli
  - grunt build
  - aws s3 sync ./dist/ s3://backbone-flickr.com/ --acl public-read
